### ISSUE TITLE
Client freeze when shift-clicking gravel into null charm (1.12.2 - 1.7.176)

### ISSUE THREAD

**Issue by xenoflot** [Darkhax-Minecraft/Dark-Utilities#121]
As per the subject, I lined up 5 blocks I want to be nullified, held down shift and ran across them. On the very first, the client just froze and had to be terminated. In the name of science, I was able to replicate the problem. Moving the blocks in one at a time by left-clicking is no problem, but shift-clicking causes a freeze. 

Playing AllTheMods3 ver 4.3 but I have no access to server logs.
DarkUtils 1.7.176
Forge 14.23.0.2512
InvTweaks 1.63+release.109.220f

**Comment by Spiker985** [comment]
I am also having this bug in the FTB Horizons 3 pack. I do have server logs available though it doesn't appear to log in the server, so I imagine it's client side only.

DarkUtils 1.7.181
Forge 14.23.0.2532
InvTweaks 1.63+release.109.220f

**Comment by darkhax** [comment]
This is fixed in the [latest alpha](https://minecraft.curseforge.com/projects/dark-utilities/files/2506687). If the file is not available for download, wait for Curse to approve it.

**Comment by xenoflot** [comment]
This is still happening in 1.7.181.  No CTD, just an endless Windows spinner.

**Comment by darkhax** [comment]
@xenoflot Please make sure you are using the latest build before reporting bugs. This issue was initially happening with 1.7.181, so of course you're still going to have the issue if you use 1.7.181.

**Comment by xenoflot** [comment]
... I could've sworn that 1.7.181 was more recent than 1.7.181... I remember checking the version that Spiker reported! My brain must've been having a serious issue yesterday. Sorry about that.
