### ISSUE TITLE
Player Damage Traps seem to break blaze AI

### ISSUE THREAD

**Issue by MissPotato** [Darkhax-Minecraft/Dark-Utilities#243]
When a blaze gets damaged by the Player Damage Trap all blazes within their aggro range will start flying upwards seemingly forever. The only solution is to have them aggro on a player. CC:Tweaked turtles seem to handle blazes fine so they may have a special case in their fake player?

I'm playing the pack "Enigmatica 6 - EP 6 version 0.3.9" which uses dark utils version 7.0.7. It is hosted on a dedicated server. https://i.imgur.com/yVCqYQ3.png

**Comment by Darkhax** [comment]
This should be fixed in the new release. https://www.curseforge.com/minecraft/mc-mods/dark-utilities/files/3183636

**Comment by AryuSyrius** [comment]
This is still broken for me. When a blaze is killed by it, the rest seem to fly up. I am running version 7.0.8. I did destroy the plates and craft new ones, just incase that was the issue.

**Comment by Darkhax** [comment]
@AryuSyrius It was fixed in 8.0.2 so of course it's still broken for you. You didn't update.

**Comment by AryuSyrius** [comment]
Ah, I missed that when I was looking at the changelog in the curseforge client. My bad.
